image: Ubuntu

version: 0.1.0.{build}

# Only clone the current branch and no history
clone_depth: 1

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

environment:
  # DOCKER_BUILDKIT: 1
  DOCKER_PASS:
    secure: 7xusxxMFy9iURl0Ktuzri5XyT3/NDKlsU3kkfJ+Sq90=

cache:
  - /var/run/docker.sock -> Dockerfile, local.Dockerfile

skip_commits:
  files:
    - README.md

build:
  verbosity: quiet

build_script:
  - ps: docker image build -f local.Dockerfile -t dotnetru/devactivator-local:latest -t dotnetru/devactivator-local:$env:APPVEYOR_BUILD_VERSION .
  - ps: docker image build -t dotnetru/devactivator:latest -t dotnetru/devactivator:$env:APPVEYOR_BUILD_VERSION .

test: off

deploy_script:
  - ps: $env:DOCKER_PASS | docker login --username dotnetrucd --password-stdin
  - ps: docker push dotnetru/devactivator-local:latest
  - ps: docker push dotnetru/devactivator-local:$env:APPVEYOR_BUILD_VERSION
  - ps: docker push dotnetru/devactivator:latest
  - ps: docker push dotnetru/devactivator:$env:APPVEYOR_BUILD_VERSION
