export const API_ENDPOINTS = {
    addFriendUrl: 'api/Friend/AddFriend',
    addMeetupUrl: 'api/Meetup/AddMeetup',
    addSpeakerUrl: 'api/Speaker/AddSpeaker',
    addTalkUrl: 'api/Talk/AddTalk',
    addVenueUrl: 'api/Venue/AddVenue',
    getCompositeMeetupUrl: 'api/Composite/GetMeetup/{{meetupId}}',
    saveCompositeMeetupUrl: 'api/Composite/SaveMeetup/{{meetupId}}',
    getFriendUrl: 'api/Friend/GetFriend/{{friendId}}',
    getFriendsUrl: 'api/Friend/GetFriends',
    getMeetupUrl: 'api/Meetup/GetMeetup/{{meetupId}}',
    getMeetupsUrl: 'api/Meetup/GetMeetups',
    getSpeakerUrl: 'api/Speaker/GetSpeaker/{{speakerId}}',
    getSpeakersUrl: 'api/Speaker/GetSpeakers',
    getTalkUrl: 'api/Talk/GetTalk/{{talkId}}',
    getTalksUrl: 'api/Talk/GetTalks',
    getVenueUrl: 'api/Venue/GetVenue/{{venueId}}',
    getVenuesUrl: 'api/Venue/GetVenues',
    storeFriendAvatarUrl: 'api/File/StoreFriendAvatar/{{friendId}}',
    storeSpeakerAvatarUrl: 'api/File/StoreSpeakerAvatar/{{speakerId}}',
    updateFriendUrl: 'api/Friend/UpdateFriend',
    updateMeetupUrl: 'api/Meetup/UpdateMeetup',
    updateSpeakerUrl: 'api/Speaker/UpdateSpeaker',
    updateTalkUrl: 'api/Talk/UpdateTalk',
    updateVenueUrl: 'api/Venue/UpdateVenue',
};
