export const LABELS = {
    ADDRESS: 'Адрес',
    BLOG_URL: 'Ссылка на блог',
    CODE_URL: 'Ссылка на код',
    COMPANY: 'Компания',
    COMPANY_URL: 'Сайт компании',
    CONTACTS_URL: 'Ссылка на контакты',
    DESCRIPTION: 'Описание',
    GIT_HUB_URL: 'Ссылка на GitHub',
    HABR_URL: 'Ссылка на хабр',
    IDENTITY: 'Идентификатор',
    MAP_URL: 'Ссылка на карту',
    NAME: 'Имя',
    SLIDES_URL: 'Ссылка на слайды',
    TITLE: 'Название',
    TWITTER_URL: 'Ссылка на твиттер',
    URL: 'Ссылка',
    VIDEO_URL: 'Ссылка на видео',
};
